# Generated by Django 4.2.6 on 2023-12-06 02:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(help_text='Enter a license plate (e.g. LLL-DDDD or LLL-DDD).', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid license plate in the format LLL-DDD or LLL-DDDD.', regex='^[A-Z]{3}-\\d{3,4}$')]),
        ),
    ]
